
package com.boco.app.simbaWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AppCenterWSPortType", targetNamespace = "http://ws.appcenter.isimba.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AppCenterWSPortType {


    /**
     * 
     * @param args1
     * @param args0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:request")
    @WebResult(targetNamespace = "http://ws.appcenter.isimba.cn")
    @RequestWrapper(localName = "request", targetNamespace = "http://ws.appcenter.isimba.cn", className = "cn.isimba.appcenter.ws.Request")
    @ResponseWrapper(localName = "requestResponse", targetNamespace = "http://ws.appcenter.isimba.cn", className = "cn.isimba.appcenter.ws.RequestResponse")
    public String request(
        @WebParam(name = "args0", targetNamespace = "http://ws.appcenter.isimba.cn")
        String args0,
        @WebParam(name = "args1", targetNamespace = "http://ws.appcenter.isimba.cn")
        String args1);

}
